<script context="module" lang="ts">
    import {getContext, setContext} from "svelte";
    import type {Load} from "@sveltejs/kit";

    import {map_navigation_items} from "@kahi-docs/config";
    import {set_context_hack} from "@kahi-docs/shared";

    // TODO: / NOTE: I would really like to have this live in an API
    // route, however icons as Svelte Components can't exist then
    import NAVIGATION_CONFIG from "../../.kahi-docs/navigation.config";

    import type {IApplicationConfigGet} from "../shared/api";

    set_context_hack(getContext, setContext);

    export const load: Load = async ({fetch}) => {
        const response = await fetch("/api/v2/configuration/application.json");
        const data = (await response.json()) as IApplicationConfigGet;
        const application_config = data.data;

        const items = map_navigation_items<INavigationBar>(NAVIGATION_CONFIG.application, {
            base: application_config.urls.base,
        });

        return {
            context: {
                application_config,
            },

            props: {
                application_config,
                items,
            },
        };
    };
</script>

<script lang="ts">
    import type {IApplicationConfig, INavigationBar} from "@kahi-docs/config";
    import {
        set_application_config,
        set_app_navigation,
        set_partials_config,
    } from "@kahi-docs/shared";

    import PARTIALS_CONFIG from "../../.kahi-docs/partials.config";

    export let application_config: IApplicationConfig;
    export let items: INavigationBar[];

    set_application_config(application_config);
    set_partials_config(PARTIALS_CONFIG);

    set_app_navigation(items);
</script>

<slot />

<style>
    :global(body),
    :global(html) {
        height: 100%;
    }

    /**
     * NOTE: These styles can be used in multiple, blog, docs, landing page, etc. And
     * typically auto generated by the Markdown parser with raw HTML. So they're placed
     * here instead of a Component.
     */

    :global(.snippet-highlight),
    :global(.snippet-repl) {
        width: 100%;

        border: 1px solid rgb(var(--palette-foreground-text), 0.3);
        border-radius: 0.375rem;
    }
</style>
