<script>
    import "@kahi-ui/framework/dist/kahi-ui.framework.css";
    import "@kahi-ui/framework/dist/kahi-ui.theme.default.css";

    import "prismjs/themes/prism-tomorrow.css";

    import {browser} from "$app/env";
    import {htmlmode} from "@kahi-ui/framework";

    import {preferencetheme} from "@kahi-docs/shared";

    import GlobalPrerender from "../lib/components/GlobalPrerender.svelte";
    import PageMetadata from "../lib/components/PageMetadata.svelte";

    const _htmlmode = htmlmode();
    $: if (browser) $_htmlmode = $preferencetheme ?? "";
</script>

<GlobalPrerender />
<PageMetadata />

<slot />

<style>
    :global(body),
    :global(html) {
        height: 100%;
    }

    /**
     * NOTE: These styles can be used in multiple places, blog, docs, landing page, etc.
     * And typically auto generated by the Markdown parser with raw HTML. So they're
     * placed here instead of a Component.
     */

    :global(.highlight),
    :global(.repl-snippet) {
        position: relative;

        width: 100%;
        max-height: 30rem;

        border: var(--sizes-borders-tiny) solid hsla(var(--palettes-auto-foreground-bolder), 0.5);
        border-radius: calc(var(--radius-small) * 1rem);
    }

    :global(.highlight[data-mode="repl"]),
    :global(.repl-snippet) {
        /** NOTE: REPLs are fixed heights, so we need to set documentation snippets to be likewise */

        height: 30rem;
    }

    :global(.repl-snippet) {
        z-index: 0;
    }
</style>
