<script lang="ts">
    // ...
</script>

<slot />

<style>
    :global(body),
    :global(html) {
        height: 100%;
    }

    /**
     * NOTE: These styles can be used in multiple, blog, docs, landing page, etc. And
     * typically auto generated by the Markdown parser with raw HTML. So they're placed
     * here instead of a Component.
     */

    :global(.snippet-highlight),
    :global(.snippet-repl) {
        width: 100%;

        border: 1px solid rgba(var(--palette-inverse-lightest), 0.5);
        border-radius: var(--radius-small);
    }
</style>
