<script>
    import "prismjs/themes/prism-tomorrow.css";

    import "@kahi-ui/framework/dist/kahi-ui.framework.css";
    import "@kahi-ui/framework/dist/kahi-ui.theme.default.css";

    import {browser} from "$app/env";
    import {htmlmode} from "@kahi-ui/framework";

    import {preferencetheme} from "@kahi-docs/shared";

    import GlobalPrerender from "../lib/components/GlobalPrerender.svelte";

    const _htmlmode = htmlmode();
    $: if (browser) $_htmlmode = $preferencetheme ?? "";
</script>

<GlobalPrerender />

<slot />

<style>
    :global(body),
    :global(html) {
        height: 100%;
    }

    /**
     * NOTE: These styles can be used in multiple, blog, docs, landing page, etc. And
     * typically auto generated by the Markdown parser with raw HTML. So they're placed
     * here instead of a Component.
     */

    :global([class*="language-"]) {
        font-size: var(--font-content-size-root-small) !important;
        line-height: var(--font-content-line-height-small) !important;
    }

    :global([class*="language-"] > code) {
        font-size: 1em;
    }

    :global(.highlight),
    :global(.repl-snippet) {
        position: relative;

        width: 100%;
        max-height: 30rem;

        border: 1px solid rgba(var(--palette-inverse-off-lightest), 0.5);
        border-radius: var(--radius-small);
    }

    :global(.highlight[data-mode="repl"]),
    :global(.repl-snippet) {
        /** NOTE: REPLs are fixed heights, so we need to set documentation snippets to be likewise */

        height: 30rem;
    }

    :global(.repl-snippet) {
        z-index: 0;
    }
</style>
